### ISSUE TITLE
How to use it？

### ISSUE THREAD

**Issue by cld378632668** [hmt1203/doc88-download#5]

**Comment by brovary3154** [comment]
This is how I believe one is to use it.  I get errors that I don't really understand though.

root@test:/home/pi/doc88-download# node index.js http://www.doc88.com/p-1738513521042.html

/home/pi/doc88-download/index.js:72
' + details.method + ' - ' + details.url + ' [' + details.resourceType + `]`);
^
SyntaxError: Unexpected token ILLEGAL
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:906:3
root@test:/home/pi/doc88-download#
